name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: download latest.json
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{github.event.repository.name}},
          file: latest.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update latest.json notes
        uses: jossef/action-set-json-field@v2.1
        with:
          file: latest.json
          field: notes
          value: ${{github.event.pull_request.body}}
      - name: Upload latest.json
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "latest.md"
          overwrite: true
